// Auto-generated by ExcelToJson. Do not edit manually.
using System;

namespace GameData
{
    [Serializable]
    public class CharacterData
    {
        public int id;
        public string name;
        public int hp;
        public int attack;
        public int defense;
        public float speed;
        public int level;
        public string[] skills;
    }
}
