// Auto-generated by ExcelToJson. Do not edit manually.
using System;

namespace GameData
{
    [Serializable]
    public class ItemData
    {
        public int id;
        public string name;
        public string type;
        public int attack;
        public int defense;
        public float price;
        public string[] tags;
        public string description;
    }
}
